name: Apply create projects
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GITHUB_RUN_ID to apply'
        required: true

defaults:
  run:
    shell: bash
    working-directory: 010-create-projects

jobs:
  apply-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_email: ${{ secrets.CREATE_PROJECTS_GCP_EMAIL }}
          service_account_key: ${{ secrets.CREATE_PROJECTS_GCP_KEY }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2
          cli_config_credentials_token: ${{ secrets.CREATE_PROJECTS_TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 010-create-projects.yml
          name: ${{ github.event.inputs.run_id }}
          path: 010-create-projects

      - name: Terraform Apply
        id: apply
        run: terraform apply ${{ github.event.inputs.run_id }}
