---
name: Plan create projects
on:
  push:
    branches:
      - '*'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

---
name: Apply create projects
on:
  workflow_dispatch

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
