name: Plan create projects
on:
  push:
    paths:
      - '010-environment/*'
      - '.github/workflows/010-create-projects.yml'
    branches:
      - '*'

defaults:
  run:
    shell: bash
    working-directory: 010-environment

jobs:
  plan-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_email: ${{ secrets.CREATE_ENVIRONMENT_GCP_EMAIL }}
          service_account_key: ${{ secrets.CREATE_ENVIRONMENT_GCP_KEY }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2
          cli_config_credentials_token: ${{ secrets.CREATE_ENVIRONMENT_TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=${{ github.run_id }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.run_id }}
          path: 010-environment/${{ github.run_id }}

  apply-action:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_email: ${{ secrets.CREATE_ENVIRONMENT_GCP_EMAIL }}
          service_account_key: ${{ secrets.CREATE_ENVIRONMENT_GCP_KEY }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2
          cli_config_credentials_token: ${{ secrets.CREATE_ENVIRONMENT_TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 010-create-projects.yml
          name: ${{ github.run_id }}
          path: 010-environment

      - name: Terraform Apply
        id: apply
        run: terraform apply ${{ github.run_id }}
