name: Apply create projects
on:
  workflow_dispatch

defaults:
  run:
    shell: bash
    working-directory: 010-create-projects

jobs:
  apply-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2
          cli_config_credentials_token: ${{ secrets.CREATE_PROJECTS_TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Init
        id: init
        run: terraform apply -auto-approve
