name: Plan create projects
on:
  push:
    paths:
      - '010-create-projects'
      - '.github/workflows/010-create-projects.yml'
      - '.github/workflows/010-create-projects-apply.yml'
    branches:
      - '*'

defaults:
  run:
    shell: bash
    working-directory: 010-create-projects


jobs:
  plan-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2
          cli_config_credentials_token: ${{ secrets.CREATE_PROJECTS_TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
